version: '2'
services:
  vkbot:
    build:
      context: ./VkGroupBot
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./VkGroupBot:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"

  tgbot:
    build:
      context: ./TgBot
      dockerfile: Dockerfile
    command: python3 bot.py
    volumes:
      - ./TgBot:/usr/app/
    ports:
      - "8002:8002"

